name: Buildifier check
on: [workflow_call]

jobs:
  bazel-6:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Download buildifier.
        run: |
          curl -L 'https://github.com/bazelbuild/buildtools/releases/download/v7.1.1/buildifier-linux-amd64' > buildifier
          chmod +x buildifier
          sudo mv buildifier /usr/bin/

      - name: Checkout code.
        uses: actions/checkout@v4

      - name: Run buildifier.
        run: |
          buildifier -mode check -r .
